#!/usr/bin/env python3
"""Generate an IDE-only CMakeLists.txt from compile_commands.json.

For CMake-aware C IDEs (e.g. CLion). NOTE: Rider cannot load this either --
it has no "Open as Project" for CMake/compile_commands.json C projects (see
docs/IDE_SETUP.md). This file exists ONLY for IDE indexing/navigation; the real build is
still Makefile.cbm. Re-run after scripts/gen_compile_commands.sh.
"""
import json, os, shlex

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
db = json.load(open(os.path.join(ROOT, "compile_commands.json")))

seen, lines = set(), []
for e in db:
    f = os.path.relpath(os.path.join(e["directory"], e["file"]), ROOT)
    if f in seen or not os.path.exists(os.path.join(ROOT, f)):
        continue
    seen.add(f)
    args = e.get("arguments") or shlex.split(e["command"])
    incs = [a[2:] for a in args if a.startswith("-I")]
    defs = [a[2:] for a in args if a.startswith("-D")]
    q = lambda xs: " ".join('"%s"' % x.replace('"', '\\"') for x in xs)
    props = []
    if incs:
        props.append("INCLUDE_DIRECTORIES " + '"%s"' % ";".join(
            os.path.join("${CMAKE_SOURCE_DIR}", i) if not os.path.isabs(i) else i for i in incs))
    if defs:
        props.append("COMPILE_DEFINITIONS " + '"%s"' % ";".join(d.replace('"', '\\"') for d in defs))
    if props:
        lines.append('set_source_files_properties("%s" PROPERTIES %s)' % (f, " ".join(props)))

out = [
    "# AUTO-GENERATED by scripts/gen_ide_cmake.py -- IDE indexing only.",
    "# The real build is Makefile.cbm. Do not use this to build.",
    "cmake_minimum_required(VERSION 3.16)",
    "project(codebase_memory_ide C)",
    "set(CMAKE_C_STANDARD 11)",
    "add_library(cbm_ide_index OBJECT",
    *['    "%s"' % f for f in sorted(seen)],
    ")",
    "set_target_properties(cbm_ide_index PROPERTIES EXCLUDE_FROM_ALL TRUE)",
    *lines,
    "",
]
open(os.path.join(ROOT, "CMakeLists.txt"), "w").write("\n".join(out))
print("wrote CMakeLists.txt with %d sources" % len(seen))

